### ISSUE TITLE
[ERROR] File exists (os error 17) installing R 3.5.3

### ISSUE THREAD

**Issue by RuiyuRayWang** [r-lib/rig#124]
Hi, while installing a legacy version of R (3.5.3) I encountered the following error

```
$ rig add 3.5.3
[INFO] Running `sudo` for adding new R versions. This might need your password.
[sudo] password for xxxxxx: 
[INFO] Downloading https://cdn.rstudio.com/r/ubuntu-2004/pkgs/r-3.5.3_1_amd64.deb ->
    /tmp/rig/r-3.5.3_1_amd64.deb
[INFO] Running apt-get update
--nnn-- Start of apt-get output -------------------
Hit:1 https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64  InRelease
Hit:2 https://dl.google.com/linux/chrome/deb stable InRelease                  
Hit:3 https://download.docker.com/linux/ubuntu focal InRelease                 
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease             
Hit:5 http://cn.archive.ubuntu.com/ubuntu focal InRelease     
Hit:6 http://cn.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:7 http://cn.archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
--uuu-- End of apt-get output ---------------------
[INFO] Running apt-get install
--nnn-- Start of apt-get output -------------------
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gdebi-core is already the newest version (0.9.5.7+nmu3).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
--uuu-- End of apt-get output ---------------------
[INFO] Running gdebi
--nnn-- Start of gdebi output ---------------------
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
Selecting previously unselected package r-3.5.3.
(Reading database ... 311120 files and directories currently installed.)
Preparing to unpack /tmp/rig/r-3.5.3_1_amd64.deb ...
Unpacking r-3.5.3 (1) ...
Setting up r-3.5.3 (1) ...
--uuu-- End of gdebi output -----------------------
[ERROR] File exists (os error 17)
```

After which `rig list` says
```
$ rig list
3.5.3
3.6.2
3.6.3
4.0.5
4.1.0
4.2.0
```

But the R version cannot be loaded.
```
$ rig default 3.5.3
[INFO] Running `sudo` for setting the default R version. This might need your password.
[ERROR] File exists (os error 17)
```

Does anyone encounter the same problem?

Ray

**Comment by gaborcsardi** [comment]
I think this is already fixed in the latest version of rig, what version are you using?

**Comment by RuiyuRayWang** [comment]
```
$rig --version
RIIG -- The R Installation Manager 0.4.2
```

I'll update to the latest version. Thanks!

**Comment by RuiyuRayWang** [comment]
Hi Gabor,

Previously I was using 0.4.2.
```
$rig --version
RIIG -- The R Installation Manager 0.4.2
```

Now I updated to rig 0.5.2 but the issue persists.
```
~$ rig --version
RIG -- The R Installation Manager 0.5.2
~$ rig default 3.5.3
[INFO] Running `sudo` for setting the default R version. This might need your password.
~$ rig remove 3.5.3
[INFO] Running `sudo` for removing R versions. This might need your password.
[INFO] Removing r-3.5.3 package
[INFO] > Reading package lists...
[INFO] > Building dependency tree...
[INFO] > Reading state information...
[INFO] > The following packages will be REMOVED:
[INFO] >   r-3.5.3*
[INFO] > 0 upgraded, 0 newly installed, 1 to remove and 10 not upgraded.
[INFO] > After this operation, 89.6 MB disk space will be freed.
[INFO] > (Reading database ... 313092 files and directories currently installed.)
[INFO] > Removing r-3.5.3 (1) ...
~$ rig default 4.1.0
[INFO] Running `sudo` for setting the default R version. This might need your password.
[ERROR] File exists (os error 17)
~$ R --version
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
```

Best,
Ray

**Comment by ifendo** [comment]
I also got the similar issue on Mac M1 with rig version 0.5.3, any idea on how to solve it @gaborcsardi ? thank you very much

**Comment by gaborcsardi** [comment]
@ifendo You are on a different OS, it is unlikely that it is the same issue, can you please open another issue with the details?

**Comment by ifendo** [comment]
Thank you very much for your quick response. I have created a new issue #157 as you suggested.
